/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function version(): string
export declare function libopusVersion(): string
export declare function registerOpus(): void
